### PR TITLE
Add erlang includes on macOS

### PR DESCRIPTION
**Pull request by emlyn**
This failed to build for me on macOS unless I added the erlang include directory to the build. The directory assumes erlang is installed via Homebrew, and unfortunately has the full version in the path so it will need updating whenever Homebrew updates erlang, but I'm not sure if there's a better way of doing this.

### CODE REVIEW

**Comment by llloret** [comment]
Hi, @emlyn, thank you for reporting this.

@rbnpi and @samaaron have been working on this (I don't have access to macOS), and I am not sure what the current advice is on this. Robin, Sam, can you please comment? Obviously I would like to use the proper approach here, and then do the same on the sonic_pi repo itself.

**Comment by samaaron** [comment]
We haven't really got a solution for this yet. People will install Erlang from a variety of places, not just Homebrew. 

@llloret we need a nice solution that allows people to point the CMakeLists.txt file to their Erlang distro's header files.

Alternatively we can do what we currently do with Windows and include an Erlang binary and header in the tree. 

I'm open to suggestions here. I'm not really a cmake expert and don't yet know what the canonical way of doing this is.

**Comment by emlyn** [comment]
I'm not sure either what the canonical way of doing this is, but another option might be a config script that either searches some common locations for it (and other external dependencies), or takes the location as an argument, and then updates the CMakeLists.txt or other config file.

**Comment by llloret** [comment]
We could use a variable in CMakeLists that people can set if necessary. I
can also have a look and see if there is already a cmake module that looks
for erlang.

Not sure if this is the same that you were proposing, @emlyn.

**Comment by emlyn** [comment]
I was thinking something along the lines of the Sonic Pi [config script](https://github.com/samaaron/sonic-pi/blob/main/app/gui/qt/mac-config.sh) searching for it and writing the location somewhere, but if there is a cmake module that does that it would be easier.

**Comment by samaaron** [comment]
@llloret I think a variable would be great!

**Comment by samaaron** [comment]
I think it's perfectly reasonable to ask people to enter the locations of some of the deps when they first set the dev environment up :-)

**Comment by emlyn** [comment]
I agree, that would be simplest, and is perfectly reasonable.
If possible though, it would be nice if these locations were all set in a single file to make setup easier, which ideally wouldn't be checked into git.

**Comment by llloret** [comment]
Ok, I'll have a look at adding a variable for this on CMakeLists.txt.

**Comment by rbnpi** [comment]
I just added a line to CMakeLists.txt
```
include_directories("/usr/local/lib/erlang/usr/include")
```
which was where brew had installed the erlang header files required. Since I largely still build on MacOS by hand this suited me. Sam's scripts usually refer to build from source installs rather than brew installed stuff. I think a script would be quite difficult to cope with lots of different ways of getting the bits. I think including stuff as in the windows build would be a good idea. Means everyone is using the same stuff.

**Comment by llloret** [comment]
@rbnpi , @samaaron , @emlyn , I have added a variable to CMakeLists.txt so that you can set the erlang include directories. I have done this for both Mac and Windows. DO you mind giving it a try and let me know if it is what you were expecting?
It is in this branch: https://github.com/llloret/sp_midi/tree/cmake_macos_erlang_include_var.
Thank you!

**Comment by emlyn** [comment]
@rbnpi I didn't notice that the headers are also linked from there - that's a much better path than the one I used as it should be independent of version.

@llloret thanks, I'll give that a go. Is that just a normal environment variable that I need to set before calling CMake?

**Comment by llloret** [comment]
Thank you. No, it's not an env variable. If you use ccmake, it should appear in the list of things that you can set. Or you can set it from outside the cmake command line, as described here for example: https://stackoverflow.com/questions/52071882/how-to-pass-a-variable-from-command-line-to-a-cmake-toolhain-file.

Let me know how it goes.

**Comment by emlyn** [comment]
I checked that branch out into my Sonic Pi working directory (to replace the one in there) and changed [this line](https://github.com/samaaron/sonic-pi/blob/12cdfef418f578f9f8634d682a9d836312595a5b/app/gui/qt/external/linux_build_externals.sh#L11) to:
`cmake -D ERLANG_INCLUDE_PATH=/usr/local/lib/erlang/usr/include --build . --target sp_midi`
and reran `sh mac-prebuild.sh`, but it now errors with:
```
Building sp_midi...
CMake Error: The source directory "/<path>/sonic-pi/app/gui/qt/external/build/sp_midi" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```
That directory does not exist, but there is one called `sp_midi-prefix`. I tried manually creating the directory it complains about but then I just get:
```
CMake Error: The source directory "/<path>/sonic-pi/app/gui/qt/external/build/--target" does not exist.
```
I'm not very familiar with cmake, so I'm getting a bit out of my depth. I'm not sure why that's failing now when it ran before.

**Comment by llloret** [comment]
Um, interesting. If you don't mind, what I'll do is close this pr, create
an issue with your current problem and create a new pr based on this new
branch, and e can continue the discussion there. Is that ok?

**Comment by emlyn** [comment]
That sounds good. I'm not sure if my current problem is something up with sp_midi or just me doing something wrong.

**Comment by llloret** [comment]
@emlyn , I think the issue you had might have been because you had a space between the -D and the variable name... It seems cmake is quite picky about that, anyway, I'll update the other PR with your previous input there and merge

**Pull request closed without merging**
